name: build-deno
on:
  pull_request:
  push:
    branches: [master]
    tags:
      - .*

jobs:
  build_test_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run compile:deno
      - run: echo 'NEED SOME KIND OF DENO DEPLOY STEP HERE HMMM'

